### ISSUE TITLE
Get Fridge

### ISSUE THREAD

**Issue by eL0ck** [timandrach-worldtour/tyrellstreet#1]
### Contacted
- [x] [Fisher&Paykel fridge](https://www.facebook.com/marketplace/item/1280027498812359/?ref=messenger_banner)
[](url)
- [x] [Westinghouse WTB2800WB 280L Fridge](https://www.facebook.com/marketplace/item/822717208113157/?ref=messenger_banner)

Waiting for responses

**Comment by eL0ck** [comment]
Westinghouse is gone but Guy will contact tomorrow about other fridges.

**Comment by eL0ck** [comment]
F&P Guy  on standby.  Confirming when is suitable to go to Belmont.

**Comment by rachierose** [comment]
So our max size is 170x70 - the Westinghouse one is still up on FB, and it is less than that. Maybe worth giving him another call @eL0ck and also seeing what else he has available for those dimensions.
Another criteria for me is 3.5 energy stars or more, which the Westinghouse is, but just something to bear in mind for other fridges x

**Comment by eL0ck** [comment]
<img width="240" alt="Screen Shot 2019-05-09 at 10 58 47 am" src="https://user-images.githubusercontent.com/4349566/57420165-a51f9400-7249-11e9-9438-34fc87cec973.png">

haha!

**Comment by eL0ck** [comment]
I sent her a message

**Comment by eL0ck** [comment]
btw, the westinghouse is still available.  Asked if he's available tonight to take a look.

**Comment by eL0ck** [comment]
Westinghouse guy is in Cardiff and available at 6pm.  Are you keen to take a look tonight?
@rachierose 

22 Murray rd,
Cardiff

**Comment by rachierose** [comment]
Yes @eL0ck - I will try to reschedule the table and chairs to 7ish
