### ISSUE TITLE
Towels

### ISSUE THREAD

**Issue by rachierose** [timandrach-worldtour/tyrellstreet#10]

**Comment by rachierose** [comment]
I like the Australian House & Garden natural cotton bath towels, see:
https://www.myer.com.au/c/home/allbathroom/bath-towels?facets=mfName_ntk_cs%253A%2522Australian%2BHouse%2B%2526%2BGarden%2522&pageNumber=1
Thinking:
- four towels (EITHER: one celestial blue, one charcoal, one natural, one dusty pink OR: two of two colours - maybe celestial blue  and charcoal)
- four face washers (either four matching if we get four colours, or contrasting if we choose two)

**Comment by rachierose** [comment]
Towel price is $35 each / but purchase on sale (currently 30% off)

**Comment by rachierose** [comment]
Please review comments @eL0ck

**Comment by eL0ck** [comment]
All the colors on that page look great @rachierose.  Go for it
