### ISSUE TITLE
Shelves

### ISSUE THREAD

**Issue by rachierose** [timandrach-worldtour/tyrellstreet#13]
For next to front door. Book shelves / big enough for Kombucha home

**Comment by rachierose** [comment]
What do you think of [this]([https://www.facebook.com/marketplace/item/2186850024868975/]) @eL0ck even for our plants on the deck

**Comment by eL0ck** [comment]
oh no! Its already sold!

Looks good though.

P.S nice work with the link markdown up there ;)

**Comment by rachierose** [comment]
Buy industrial shelves from the same secondhand shop as coffee table @eL0ck
