### ISSUE TITLE
Cutlery

### ISSUE THREAD

**Issue by eL0ck** [timandrach-worldtour/tyrellstreet#2]
https://www.facebook.com/marketplace/item/413434532530068/?ref=messenger_banner

**Comment by eL0ck** [comment]
Contacted lady.  Waiting for response.

I'd offer $50 on the spot

**Comment by rachierose** [comment]
[Another option]([url](https://www.facebook.com/marketplace/item/570520800088049/)) if the first fails - could do on weekend, offer $100

**Comment by eL0ck** [comment]
This look really nice.  I prefer slimmer forks.

**Comment by eL0ck** [comment]
Messaged the lady again.

Messaged the other set on the Central Coast too.

**Comment by eL0ck** [comment]
Hooked you up with Rogerio the guy selling the [2nd set we looked at](https://www.facebook.com/marketplace/item/570520800088049/?ref=messenger_banner)

**Comment by rachierose** [comment]
@eL0ck West Gosford is a long way out of the way... might see if he's heading into Bateau Bay or Tuggerah otherwise will give it a miss

**Comment by rachierose** [comment]
@eL0ck sorry to be flakey re that cutlery - to be honest the more I look at it the less I like it - let's see if he can meet me. I'll check the secondhand shops down there too

**Comment by rachierose** [comment]
Would need to get knives but in Bateau Bay & very cheap https://www.facebook.com/marketplace/item/2070306886386487/
