### ISSUE TITLE
Buy Sofa

### ISSUE THREAD

**Issue by eL0ck** [timandrach-worldtour/tyrellstreet#3]

**Comment by eL0ck** [comment]
I have a tendancy to assume things gumtree/facebook are bargains.  Check out [this site](https://www.catch.com.au/shop/furniture/living-room/sofas-lounge-suites).  Lots of cheap junk (and reasonable stuff too!) for the prices we are looking at.

If we see something 2nd hand we should find its 'new price' before responding.

**Comment by rachierose** [comment]
@eL0ck definitely! Let me know if you see anything work checking out

**Comment by rachierose** [comment]
@eL0ck let's check [this one](https://www.facebook.com/marketplace/item/444750282958420/) out once we have the van running. It's about the length of our rug. Obviously not pay asking price

**Comment by eL0ck** [comment]
[Freedom Dahlia](https://www.freedom.com.au/furniture/living-room/sofas/23494428/dahlia-3-seat-fabric-sofa?fbclid=IwAR09-nk4QLwza7FQ6zHmJUWSr_MBFE3zDknZDHiYQTL9KmDVzvbtTzV5n24)

[FB listing](https://www.facebook.com/marketplace/item/350431645596962/?ref=messenger_share)

Would take this for $800

**Comment by eL0ck** [comment]
## Re: Small Leather couch

['this one'](https://www.facebook.com/marketplace/item/444750282958420/) you mentioned earlier would be really nice I think.  But maybe as a second option for the short wall.

Once we have a larger one we can afford to wait and keep an eye out for a bargain.

We should keep an eye on this one though

**Comment by rachierose** [comment]
Totally agree with both points!
re the Freedom Dahlia - aim for $700-$800
Also love the small leather couch - let's see if it would fit nicely once have a big one in. I think the small will be wanting it to move along - it's been advertised for a little while now and I've seen they've added it to Gumtree

**Comment by eL0ck** [comment]
## Freedom 3 seater ($630)
[link](https://www.facebook.com/marketplace/item/304630133820428/?ref=messenger_share)
Located in Castle hill.  Have messaged to ask if available in wednesday since I'll be out that way with Markie.
**She says on the listing to contact her by phone but the number is hidden**

## Velvet green couches
[link](https://www.facebook.com/marketplace/item/2231687833522810/?ref=messenger_share)
Look great but might be a saturday job since they are located in [Villawood](https://www.google.com.au/maps/dir/Kirribilli+NSW/Villawood+NSW+2163/@-33.8871001,151.0272026,12z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x6b12ae8a2b088b13:0x5017d681632bcf0!2m2!1d151.2175297!2d-33.8491363!1m5!1m1!1s0x6b12bdbc5517b589:0x5017d681632ce10!2m2!1d150.9788!2d-33.8861!3e0) making it a 2h round trip from Kirribilli

**Comment by rachierose** [comment]
Re the Freedom 3 seater - I sent you a message in Messenger with her phone number while you were still in Sydney last week - 0408 977 685.
Please follow up as I don't want to miss out

**Comment by rachierose** [comment]
Beautiful green velvet https://www.facebook.com/marketplace/item/2292587927727059/

The same as the one the woman sold https://www.gumtree.com.au/s-ad/st-ives/sofas/brilliant-sofa-with-used-only-1-year/1217492419

**Comment by rachierose** [comment]
3-seater https://www.facebook.com/marketplace/item/348088819184529/

**Comment by rachierose** [comment]
3-seater, leather
https://www.gumtree.com.au/s-ad/newport/sofas/brooklyn-three-seat-leather-sofa/1219008520

3-seater, green velvet
https://www.facebook.com/marketplace/item/2292587927727059/

3-seater, same as the one that was in Castle Hill
https://www.gumtree.com.au/s-ad/st-ives/sofas/brilliant-sofa-with-used-only-1-year/1217492419

3-seater, grey-brown
https://www.gumtree.com.au/s-ad/mosman/sofas/sofa-large-3-seater-sofa-light-brown/1218703811

**Comment by eL0ck** [comment]
[*E) 2-seater, brown leather*](https://www.gumtree.com.au/s-ad/long-jetty/sofas/brand-new-carson-tan-leather-lounge/1218341243)

**Comment by rachierose** [comment]
> **E) 2-seater, brown leather**
> https://www.gumtree.com.au/s-ad/long-jetty/sofas/brand-new-carson-tan-leather-lounge/1218341243

> ## Re: Small Leather couch
> ['this one'](https://www.facebook.com/marketplace/item/444750282958420/) you mentioned earlier would be really nice I think. But maybe as a second option for the short wall.
> 
> Once we have a larger one we can afford to wait and keep an eye out for a bargain.
> 
> We should keep an eye on this one though

Hey @eL0ck the one you just noted off Gumtree is the same you refer to above

Love it - but it's a bit short for a main sofa. You earlier suggested
