### ISSUE TITLE
Bedside lamps

### ISSUE THREAD

**Issue by rachierose** [timandrach-worldtour/tyrellstreet#6]

**Comment by rachierose** [comment]
@eL0ck some thoughts:
https://www.facebook.com/marketplace/item/2267346820190352/
https://www.facebook.com/marketplace/item/422493401909338/ (favourite)
https://www.facebook.com/marketplace/item/2319531094994405/

**Comment by eL0ck** [comment]
I'm not really into the yellow one. 
More generally, I'm have a real problem with looking directly at light bulbs

- [~~yellow~~](https://www.facebook.com/marketplace/item/2267346820190352/)
- [Gold Lamp](https://www.facebook.com/marketplace/item/422493401909338/ (favourite))
- [~~exposed Bulb~~](https://www.facebook.com/marketplace/item/2319531094994405/)
- [~~Grosse study lamp~~](https://www.gumtree.com.au/s-ad/mayfield-west/table-desk-lamps/red-metal-sly-table-lamp/1216940005)
