### ISSUE TITLE
Rug

### ISSUE THREAD

**Issue by rachierose** [timandrach-worldtour/tyrellstreet#9]

**Comment by rachierose** [comment]
Messaged about [this](https://www.facebook.com/marketplace/item/389970141592442/) rug

**Comment by eL0ck** [comment]
Its pretty small, but looks nice.

**Comment by eL0ck** [comment]
Is this really MEDIUM?
I feel like this should be LOW and pending decisions on sofa and dining table.  What are your thoughts?

**Comment by rachierose** [comment]
I agree to some extent - but with very few sofa options, and you being unsure whether we want a dining table, having something on the floor soon would really lift the room / make it cosier

**Comment by eL0ck** [comment]
.... and therefore is MEDIUM ??

**Comment by rachierose** [comment]
Looking at the earlier linked rug tomorrow in Berkeley Vale between 10 and 10.30 @eL0ck
